version: '3.7'
services:
  cerebro:
    container_name: cerebro
    image: lmenezes/cerebro:0.9.2
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://es01:9200
    networks:
      elk:
        ipv4_address: 192.168.32.11
  kibana:
    image: kibana:7.9.2
    hostname: kibana
    container_name: kibana
    environment: 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:rw
    ports:
      - 5601:5601
    networks:
      elk:
        ipv4_address: 192.168.32.12
  es01:
    image: elasticsearch:7.9.2
    container_name: es01
    environment:
      - cluster.name=geektime
      - node.name=es01
      - cluster.initial_master_nodes=es01,es02
      # - network.publish_host=elasticsearch1
      - discovery.seed_hosts=es02
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.port=9200
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
    ports:
      - 9200:9200
    networks:
      elk:
        ipv4_address: 192.168.32.2
  es02:
    image: elasticsearch:7.9.2
    container_name: es02
    environment:
      - cluster.name=geektime
      - node.name=es02
      - cluster.initial_master_nodes=es01,es02
      # - network.publish_host=elasticsearch2
      - discovery.seed_hosts=es01
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.port=9200
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
    ports:
      - 9201:9200
    networks:
      elk:
        ipv4_address: 192.168.32.3
  logstash:
      image: logstash:7.9.2
      container_name: logstash
      volumes:
          - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:rw
          - ./movies.csv:/usr/share/logstash/movies.csv
      networks:
        elk:
          ipv4_address: 192.168.32.10


volumes:
  data01:
    driver: local
  data02:
    driver: local


networks:
  elk:
    driver: bridge
    ipam: 
      config: 
        - subnet: 192.168.32.0/20
          gateway: 192.168.32.1
      